### ISSUE TITLE
Is there some input errors in your README.md?

### ISSUE THREAD

**Issue by Sungven** [nicolas-van/easy-markdown-to-github-pages#3]
# Is there some input errors in your README.md?
emm,,, I wanna ask you, in your README.md, here, you write,
___
### Create the `_.config.yml` file

That file should be created ,,,,
___
you say `_.config.yml`, but I find out that is `_config.yml` in your root repository.

Is there some input errors?

**Comment by nicolas-van** [comment]
Yep,  it was a mistake. It's fixed now. Thanks for the report.
